name: snackautomat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^3.1.0
  freezed: ^3.2.5

  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.2

  riverpod: ^3.3.2
  flutter_riverpod: ^3.3.2

  path_provider: ^2.1.6
  path: ^1.9.1

  cupertino_icons: ^1.0.8
  
  json_annotation: ^4.12.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true